version: "3.9"

services:
  notification-service:
    build: .
    container_name: notification-service
    environment:
      - DB_HOST=notification-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=notifications
      - DB_PORT=5432
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - notification-db
      - rabbitmq
    ports:
      - "3003:3003"
    networks:
      - banking_network

  notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    ports:
      - "5435:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data
    networks:
      - banking_network

volumes:
  notification_data:

networks:
  banking_network:
    external: true
