apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
data:
  PORT: "8081"
  DB_HOST: "account-db"
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "Password"
  DB_NAME: "accounts_db"
  RABBITMQ_URL: "amqp://admin:admin@rabbitmq:5672"
  CUSTOMER_SERVICE_URL: "http://customer-service:5001/customers"
