apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-transaction
  template:
    metadata:
      labels:
        app: postgres-transaction
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: "transactions"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "Password"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: transaction-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transaction-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-transaction
spec:
  selector:
    app: postgres-transaction
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
