apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-config
data:
  PORT: "3000"
  DB_HOST: "transaction-db"
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "Password"
  DB_NAME: "transactions"
  RABBITMQ_URL: "amqp://admin:admin@rabbitmq:5672"
  CUSTOMER_SERVICE_URL: "http://customer-service:5001/customers"
