apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  PORT: "5004"
  DB_HOST: "postgres-notification"
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "Password"
  DB_NAME: "notifications"
